name: Vérification du respect des spécifications

on:
  push:

# NOTE: if you need to debug these things locally, use `act` and medium installation:
# E.g:
# `act push` or `act push --container-architecture linux/amd64` (Mac M1)
#
# Installation notes at https://github.com/nektos/act
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
      with:
        version-file: .tool-versions
        version-type: strict
    - id: python-version
      run: echo "version=$(grep '^python' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.12'
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma statique et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema statique/schema-statique.json
        frictionless validate datapackage.json
    - name: Vérification du schéma dynamique et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema dynamique/schema-dynamique.json
    - name: Vérification de l'absence de liens cassés dans les schémas
      run: |
        elixir checks.exs
